// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using labpsi.gerenciadora.frota.infra.data.Context;

namespace labpsi.gerenciadora.frota.infra.data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("labpsi.gerenciadora.frota.domain.Aggregates.VeiculoAggregate.Km", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("283663c1-1fb6-4be8-b2ab-0a224c91fa7f"));

                    b.Property<DateTime>("DataChegada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateSaida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KmAtual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Km");
                });

            modelBuilder.Entity("labpsi.gerenciadora.frota.domain.Aggregates.VeiculoAggregate.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("90f3646c-cbab-418e-b2c9-3854b1285324"));

                    b.Property<int>("_ano")
                        .HasColumnName("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("_chassi")
                        .IsRequired()
                        .HasColumnName("Chassi")
                        .HasColumnType("text");

                    b.Property<string>("_cor")
                        .IsRequired()
                        .HasColumnName("Cor")
                        .HasColumnType("text");

                    b.Property<string>("_kmAtual")
                        .IsRequired()
                        .HasColumnName("KmAtual")
                        .HasColumnType("text");

                    b.Property<Guid?>("_kmId")
                        .HasColumnType("uuid");

                    b.Property<string>("_marca")
                        .IsRequired()
                        .HasColumnName("Marca")
                        .HasColumnType("text");

                    b.Property<int>("_mesIpva")
                        .HasColumnName("MesIpva")
                        .HasColumnType("integer");

                    b.Property<string>("_modelo")
                        .IsRequired()
                        .HasColumnName("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("_placa")
                        .IsRequired()
                        .HasColumnName("Placa")
                        .HasColumnType("text");

                    b.Property<string>("_renavam")
                        .IsRequired()
                        .HasColumnName("Renavam")
                        .HasColumnType("text");

                    b.Property<decimal>("_valorPago")
                        .HasColumnName("ValorPago")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("_kmId");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("labpsi.gerenciadora.frota.domain.Aggregates.VeiculoAggregate.Veiculo", b =>
                {
                    b.HasOne("labpsi.gerenciadora.frota.domain.Aggregates.VeiculoAggregate.Km", "_km")
                        .WithMany()
                        .HasForeignKey("_kmId");
                });
#pragma warning restore 612, 618
        }
    }
}
